name: "Setup Python"
description: "Setup Python environment for use with UV"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: install python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"
