[GLOBAL]
pants_version = "2.22.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
]

[python]
enable_resolves = true
interpreter_constraints = ["CPython==3.12.*"]

[source]
root_patterns = ["/"]

[cli.alias]
test-all = "test --debug tests::"
