name: Release Version

on: workflow_dispatch

jobs:
  # note that we are only bumping the version, not creating a release
  # future changes will also publish to an artifact repository
  release_version:
    environment: Release
    permissions:
      contents: write
      id-token: write
      actions: write
      checks: write
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      # basic setup
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup python
        id: setup-python
        uses: ./.github/actions/setup-python

      # commitizen versioning
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

      # get it to PyPi
      - name: Build and Publish Wheel
        run: |
          uv build
          uv publish
